"""Seed data for the Geekverse tools website."""

SEED_CATEGORIES = [
    {
        "id": "cat-dev",
        "slug": "dev",
        "name": "Dev Tools",
        "color": "#3b82f6",
        "description": "Code editors, version control, runtimes & IDEs",
    },
    {
        "id": "cat-network",
        "slug": "network",
        "name": "Networking",
        "color": "#06b6d4",
        "description": "Packet sniffers, SSH clients, scanners & VPNs",
    },
    {
        "id": "cat-security",
        "slug": "security",
        "name": "Cybersecurity",
        "color": "#ef4444",
        "description": "Pentesting, encryption, password managers & anti-malware",
    },
    {
        "id": "cat-os",
        "slug": "os",
        "name": "OS Utilities",
        "color": "#10b981",
        "description": "Power tools, archivers, automation & system tweaks",
    },
    {
        "id": "cat-ai",
        "slug": "ai",
        "name": "AI & ML",
        "color": "#a855f7",
        "description": "Local LLMs, model runners, generative AI tooling",
    },
    {
        "id": "cat-media",
        "slug": "media",
        "name": "File & Media",
        "color": "#f59e0b",
        "description": "Audio, video, image editors & file conversion",
    },
    {
        "id": "cat-hardware",
        "slug": "hardware",
        "name": "Hardware",
        "color": "#f97316",
        "description": "Monitoring, benchmarking & system info",
    },
    {
        "id": "cat-fun",
        "slug": "fun",
        "name": "Fun & Useless",
        "color": "#ec4899",
        "description": "Silly, absurd, meditative or weirdly addictive web toys",
    },
    {
        "id": "cat-comm",
        "slug": "comm",
        "name": "Communication",
        "color": "#14b8a6",
        "description": "Chat, voice, video & federated messaging clients",
    },
    {
        "id": "cat-prod",
        "slug": "prod",
        "name": "Productivity",
        "color": "#84cc16",
        "description": "Notes, knowledge bases, diagrams & second-brain tools",
    },
    {
        "id": "cat-terminal",
        "slug": "terminal",
        "name": "Terminal",
        "color": "#22d3ee",
        "description": "Terminal emulators, multiplexers & shell goodies",
    },
]


SEED_TOOLS = [
    # ---------------- DEV ----------------
    {
        "name": "Visual Studio Code",
        "category_slug": "dev",
        "description": "The most-used code editor on the planet. Extensible, fast, free.",
        "alternative_uses": ["Markdown editing", "Remote SSH dev", "Jupyter notebooks", "Git GUI"],
        "download_url": "https://code.visualstudio.com/Download",
        "homepage_url": "https://code.visualstudio.com/",
        "icon": "Code2",
        "popularity": 99,
        "is_open_source": True,
        "platforms": ["Windows", "macOS", "Linux"],
    },
    {
        "name": "Sublime Text",
        "category_slug": "dev",
        "description": "Buttery-fast native text editor with legendary multi-cursor support.",
        "alternative_uses": ["Note taking", "Log file viewing", "Quick scripting"],
        "download_url": "https://www.sublimetext.com/download",
        "homepage_url": "https://www.sublimetext.com/",
        "icon": "FileCode",
        "popularity": 78,
        "platforms": ["Windows", "macOS", "Linux"],
    },
    {
        "name": "Notepad++",
        "category_slug": "dev",
        "description": "Lightweight Windows text editor with syntax highlighting for 80+ languages.",
        "alternative_uses": ["Log analysis", "Hex editing", "Diff comparison"],
        "download_url": "https://notepad-plus-plus.org/downloads/",
        "homepage_url": "https://notepad-plus-plus.org/",
        "icon": "FileText",
        "popularity": 82,
        "is_open_source": True,
        "platforms": ["Windows"],
    },
    {
        "name": "Git",
        "category_slug": "dev",
        "description": "The distributed version control system that runs the software world.",
        "alternative_uses": ["Backup snapshots", "Config file tracking", "Writing project history"],
        "download_url": "https://git-scm.com/downloads",
        "homepage_url": "https://git-scm.com/",
        "icon": "GitBranch",
        "popularity": 100,
        "is_open_source": True,
        "platforms": ["Windows", "macOS", "Linux"],
    },
    {
        "name": "Docker Desktop",
        "category_slug": "dev",
        "description": "Run, build and ship containerized apps anywhere with one click.",
        "alternative_uses": ["Local databases", "Reproducible CI", "Sandbox malware analysis"],
        "download_url": "https://www.docker.com/products/docker-desktop/",
        "homepage_url": "https://www.docker.com/",
        "icon": "Container",
        "popularity": 95,
        "platforms": ["Windows", "macOS", "Linux"],
    },
    {
        "name": "Postman",
        "category_slug": "dev",
        "description": "The de-facto tool for testing, documenting and mocking APIs.",
        "alternative_uses": ["Load testing", "OAuth flow debugging", "Webhook inspection"],
        "download_url": "https://www.postman.com/downloads/",
        "homepage_url": "https://www.postman.com/",
        "icon": "Send",
        "popularity": 90,
        "platforms": ["Windows", "macOS", "Linux"],
    },
    {
        "name": "JetBrains Toolbox",
        "category_slug": "dev",
        "description": "Manage every JetBrains IDE (IntelliJ, PyCharm, WebStorm, etc) from one app.",
        "alternative_uses": ["Side-by-side versions", "EAP testing", "License management"],
        "download_url": "https://www.jetbrains.com/toolbox-app/",
        "homepage_url": "https://www.jetbrains.com/",
        "icon": "Boxes",
        "popularity": 80,
        "platforms": ["Windows", "macOS", "Linux"],
    },
    {
        "name": "DBeaver",
        "category_slug": "dev",
        "description": "Universal database GUI: works with Postgres, MySQL, Mongo, Redis, you name it.",
        "alternative_uses": ["Schema visualization", "Data export", "ER diagrams"],
        "download_url": "https://dbeaver.io/download/",
        "homepage_url": "https://dbeaver.io/",
        "icon": "Database",
        "popularity": 76,
        "is_open_source": True,
        "platforms": ["Windows", "macOS", "Linux"],
    },
    {
        "name": "Node.js",
        "category_slug": "dev",
        "description": "JavaScript runtime that powers most modern backends, CLIs and toolchains.",
        "alternative_uses": ["Quick HTTP servers", "Build tooling", "Scripting"],
        "download_url": "https://nodejs.org/en/download",
        "homepage_url": "https://nodejs.org/",
        "icon": "Hexagon",
        "popularity": 96,
        "is_open_source": True,
        "platforms": ["Windows", "macOS", "Linux"],
    },
    {
        "name": "Python",
        "category_slug": "dev",
        "description": "Batteries-included language used for AI, web, scripting, science, everything.",
        "alternative_uses": ["Automation", "Data analysis", "Game scripting", "Glue code"],
        "download_url": "https://www.python.org/downloads/",
        "homepage_url": "https://www.python.org/",
        "icon": "Code",
        "popularity": 98,
        "is_open_source": True,
        "platforms": ["Windows", "macOS", "Linux"],
    },
    {
        "name": "Insomnia",
        "category_slug": "dev",
        "description": "Sleek, open-source REST/GraphQL/gRPC client with a beautiful UI.",
        "alternative_uses": ["API design", "Environment variable testing", "Plugin scripting"],
        "download_url": "https://insomnia.rest/download",
        "homepage_url": "https://insomnia.rest/",
        "icon": "Moon",
        "popularity": 72,
        "is_open_source": True,
        "platforms": ["Windows", "macOS", "Linux"],
    },
    {
        "name": "RegExr",
        "category_slug": "dev",
        "description": "Interactive regex playground with cheatsheet and shared patterns.",
        "alternative_uses": ["Learning regex", "Text mining", "Validation prototyping"],
        "download_url": "https://regexr.com/",
        "homepage_url": "https://regexr.com/",
        "icon": "Regex",
        "popularity": 70,
        "is_open_source": True,
        "platforms": ["Web"],
    },

    # ---------------- NETWORK ----------------
    {
        "name": "Wireshark",
        "category_slug": "network",
        "description": "The world's foremost network protocol analyzer. See every packet.",
        "alternative_uses": ["Learning TCP/IP", "Detecting suspicious traffic", "VoIP debugging"],
        "download_url": "https://www.wireshark.org/download.html",
        "homepage_url": "https://www.wireshark.org/",
        "icon": "Activity",
        "popularity": 92,
        "is_open_source": True,
        "platforms": ["Windows", "macOS", "Linux"],
    },
    {
        "name": "Nmap",
        "category_slug": "network",
        "description": "Network scanner & host discovery used by every sysadmin and pentester.",
        "alternative_uses": ["Inventory scanning", "Security audits", "Service fingerprinting"],
        "download_url": "https://nmap.org/download.html",
        "homepage_url": "https://nmap.org/",
        "icon": "Radar",
        "popularity": 88,
        "is_open_source": True,
        "platforms": ["Windows", "macOS", "Linux"],
    },
    {
        "name": "PuTTY",
        "category_slug": "network",
        "description": "Tiny, legendary SSH/Telnet client for Windows. It just works.",
        "alternative_uses": ["Serial console", "SSH tunneling", "Key generation (PuTTYgen)"],
        "download_url": "https://www.putty.org/",
        "homepage_url": "https://www.chiark.greenend.org.uk/~sgtatham/putty/",
        "icon": "Terminal",
        "popularity": 85,
        "is_open_source": True,
        "platforms": ["Windows", "Linux"],
    },
    {
        "name": "WinSCP",
        "category_slug": "network",
        "description": "Drag-and-drop SFTP / SCP / FTP client with a powerful synchronization mode.",
        "alternative_uses": ["Server backups", "Remote editing", "Scripted uploads"],
        "download_url": "https://winscp.net/eng/download.php",
        "homepage_url": "https://winscp.net/",
        "icon": "ArrowLeftRight",
        "popularity": 74,
        "is_open_source": True,
        "platforms": ["Windows"],
    },
    {
        "name": "Angry IP Scanner",
        "category_slug": "network",
        "description": "Fast, friendly IP and port scanner. Cross-platform and free.",
        "alternative_uses": ["LAN discovery", "Finding rogue devices", "Open port audits"],
        "download_url": "https://angryip.org/download/",
        "homepage_url": "https://angryip.org/",
        "icon": "Wifi",
        "popularity": 68,
        "is_open_source": True,
        "platforms": ["Windows", "macOS", "Linux"],
    },
    {
        "name": "OpenVPN",
        "category_slug": "network",
        "description": "Battle-tested open-source VPN, the standard for self-hosted tunnels.",
        "alternative_uses": ["Site-to-site links", "Remote work access", "Geo-bypass"],
        "download_url": "https://openvpn.net/community-downloads/",
        "homepage_url": "https://openvpn.net/",
        "icon": "Shield",
        "popularity": 78,
        "is_open_source": True,
        "platforms": ["Windows", "macOS", "Linux"],
    },
    {
        "name": "Cloudflare WARP",
        "category_slug": "network",
        "description": "Fast, privacy-friendly DNS+VPN client powered by 1.1.1.1.",
        "alternative_uses": ["Bypass ISP throttling", "Encrypt mobile traffic", "DNS over HTTPS"],
        "download_url": "https://1.1.1.1/",
        "homepage_url": "https://1.1.1.1/",
        "icon": "Cloud",
        "popularity": 71,
        "platforms": ["Windows", "macOS", "Linux", "iOS", "Android"],
    },

    # ---------------- SECURITY ----------------
    {
        "name": "Kali Linux",
        "category_slug": "security",
        "description": "A Debian-based distro packed with 600+ pentesting and forensics tools.",
        "alternative_uses": ["CTF practice", "Red team labs", "Forensic recovery"],
        "download_url": "https://www.kali.org/get-kali/",
        "homepage_url": "https://www.kali.org/",
        "icon": "Skull",
        "popularity": 89,
        "is_open_source": True,
        "platforms": ["Linux", "VM", "WSL"],
    },
    {
        "name": "Metasploit Framework",
        "category_slug": "security",
        "description": "The world's most used penetration-testing framework.",
        "alternative_uses": ["Exploit development", "Vulnerability research", "Training labs"],
        "download_url": "https://www.metasploit.com/download",
        "homepage_url": "https://www.metasploit.com/",
        "icon": "Bug",
        "popularity": 81,
        "is_open_source": True,
        "platforms": ["Windows", "Linux"],
    },
    {
        "name": "Burp Suite Community",
        "category_slug": "security",
        "description": "Industry-standard web app security testing proxy.",
        "alternative_uses": ["API hacking", "Bug bounty hunting", "Request replay"],
        "download_url": "https://portswigger.net/burp/communitydownload",
        "homepage_url": "https://portswigger.net/burp",
        "icon": "Crosshair",
        "popularity": 84,
        "platforms": ["Windows", "macOS", "Linux"],
    },
    {
        "name": "KeePassXC",
        "category_slug": "security",
        "description": "Offline, open-source password manager. Your data, your vault.",
        "alternative_uses": ["TOTP storage", "Secure notes", "SSH key passphrases"],
        "download_url": "https://keepassxc.org/download/",
        "homepage_url": "https://keepassxc.org/",
        "icon": "KeyRound",
        "popularity": 75,
        "is_open_source": True,
        "platforms": ["Windows", "macOS", "Linux"],
    },
    {
        "name": "VeraCrypt",
        "category_slug": "security",
        "description": "Fork of TrueCrypt. Creates encrypted containers and full-disk volumes.",
        "alternative_uses": ["Encrypt USB sticks", "Hidden volumes", "Backups"],
        "download_url": "https://www.veracrypt.fr/en/Downloads.html",
        "homepage_url": "https://www.veracrypt.fr/",
        "icon": "Lock",
        "popularity": 70,
        "is_open_source": True,
        "platforms": ["Windows", "macOS", "Linux"],
    },
    {
        "name": "Tor Browser",
        "category_slug": "security",
        "description": "Browse the web anonymously through the Tor onion routing network.",
        "alternative_uses": ["Whistleblowing", "Censorship bypass", "Onion service hosting"],
        "download_url": "https://www.torproject.org/download/",
        "homepage_url": "https://www.torproject.org/",
        "icon": "EyeOff",
        "popularity": 82,
        "is_open_source": True,
        "platforms": ["Windows", "macOS", "Linux"],
    },
    {
        "name": "Bitwarden",
        "category_slug": "security",
        "description": "Open-source password manager that syncs across every device.",
        "alternative_uses": ["Secure sharing", "Self-hosted vaults", "2FA codes"],
        "download_url": "https://bitwarden.com/download/",
        "homepage_url": "https://bitwarden.com/",
        "icon": "Vault",
        "popularity": 87,
        "is_open_source": True,
        "platforms": ["Windows", "macOS", "Linux", "iOS", "Android"],
    },
    {
        "name": "Malwarebytes",
        "category_slug": "security",
        "description": "Specialist anti-malware for cleaning what antivirus misses.",
        "alternative_uses": ["Adware removal", "Ransomware protection", "Browser hijack cleanup"],
        "download_url": "https://www.malwarebytes.com/mwb-download",
        "homepage_url": "https://www.malwarebytes.com/",
        "icon": "ShieldAlert",
        "popularity": 73,
        "platforms": ["Windows", "macOS"],
    },

    # ---------------- OS ----------------
    {
        "name": "Microsoft PowerToys",
        "category_slug": "os",
        "description": "Power-user utilities for Windows: FancyZones, PowerRename, Color Picker, more.",
        "alternative_uses": ["Window snapping", "Bulk renaming", "Mouse highlighter"],
        "download_url": "https://github.com/microsoft/PowerToys/releases",
        "homepage_url": "https://learn.microsoft.com/en-us/windows/powertoys/",
        "icon": "Wand2",
        "popularity": 91,
        "is_open_source": True,
        "platforms": ["Windows"],
    },
    {
        "name": "7-Zip",
        "category_slug": "os",
        "description": "Free open-source archiver with industry-leading 7z compression ratio.",
        "alternative_uses": ["Encrypted archives", "Splitting files", "ISO extraction"],
        "download_url": "https://www.7-zip.org/download.html",
        "homepage_url": "https://www.7-zip.org/",
        "icon": "Archive",
        "popularity": 94,
        "is_open_source": True,
        "platforms": ["Windows", "Linux"],
    },
    {
        "name": "Rufus",
        "category_slug": "os",
        "description": "Tiny utility to create bootable USB drives from ISO files. Fast.",
        "alternative_uses": ["Live USB", "BIOS updates", "OS installers"],
        "download_url": "https://rufus.ie/",
        "homepage_url": "https://rufus.ie/",
        "icon": "Usb",
        "popularity": 86,
        "is_open_source": True,
        "platforms": ["Windows"],
    },
    {
        "name": "Ventoy",
        "category_slug": "os",
        "description": "Flash one USB once, drop in any number of ISOs, boot any of them.",
        "alternative_uses": ["Multi-distro testing", "Recovery toolkit", "WIM/IMG support"],
        "download_url": "https://www.ventoy.net/en/download.html",
        "homepage_url": "https://www.ventoy.net/",
        "icon": "HardDriveDownload",
        "popularity": 80,
        "is_open_source": True,
        "platforms": ["Windows", "Linux"],
    },
    {
        "name": "Everything Search",
        "category_slug": "os",
        "description": "Instantly find any file on your NTFS drives — by name, in milliseconds.",
        "alternative_uses": ["Disk cleanup", "Finding duplicates", "Folder size queries"],
        "download_url": "https://www.voidtools.com/downloads/",
        "homepage_url": "https://www.voidtools.com/",
        "icon": "Search",
        "popularity": 83,
        "platforms": ["Windows"],
    },
    {
        "name": "AutoHotkey",
        "category_slug": "os",
        "description": "Scriptable automation for Windows. Remap keys, build macros, automate anything.",
        "alternative_uses": ["Hotkeys", "Auto-clickers", "GUI bots"],
        "download_url": "https://www.autohotkey.com/download/",
        "homepage_url": "https://www.autohotkey.com/",
        "icon": "Keyboard",
        "popularity": 77,
        "is_open_source": True,
        "platforms": ["Windows"],
    },
    {
        "name": "Sysinternals Suite",
        "category_slug": "os",
        "description": "Mark Russinovich's legendary toolbox: Process Explorer, Autoruns, TCPView…",
        "alternative_uses": ["Malware analysis", "System debugging", "Startup cleanup"],
        "download_url": "https://learn.microsoft.com/en-us/sysinternals/downloads/sysinternals-suite",
        "homepage_url": "https://learn.microsoft.com/en-us/sysinternals/",
        "icon": "Cog",
        "popularity": 88,
        "platforms": ["Windows"],
    },
    {
        "name": "Process Hacker",
        "category_slug": "os",
        "description": "Open-source Task Manager replacement on steroids.",
        "alternative_uses": ["Detecting handles", "DLL inspection", "Stopping stubborn processes"],
        "download_url": "https://processhacker.sourceforge.io/downloads.php",
        "homepage_url": "https://processhacker.sourceforge.io/",
        "icon": "Cpu",
        "popularity": 65,
        "is_open_source": True,
        "platforms": ["Windows"],
    },
    {
        "name": "Oh My Zsh",
        "category_slug": "os",
        "description": "Community framework for managing your Zsh shell config. Themes & plugins galore.",
        "alternative_uses": ["Prompt customization", "Auto-suggestions", "Git aliases"],
        "download_url": "https://ohmyz.sh/",
        "homepage_url": "https://ohmyz.sh/",
        "icon": "TerminalSquare",
        "popularity": 79,
        "is_open_source": True,
        "platforms": ["macOS", "Linux", "WSL"],
    },

    # ---------------- AI ----------------
    {
        "name": "Ollama",
        "category_slug": "ai",
        "description": "Run Llama, Mistral, Phi, DeepSeek and more locally with a single command.",
        "alternative_uses": ["Private chat", "RAG dev", "Offline coding assistant"],
        "download_url": "https://ollama.com/download",
        "homepage_url": "https://ollama.com/",
        "icon": "Bot",
        "popularity": 90,
        "is_open_source": True,
        "platforms": ["Windows", "macOS", "Linux"],
    },
    {
        "name": "LM Studio",
        "category_slug": "ai",
        "description": "Beautiful desktop UI to download and chat with local LLMs (GGUF, MLX).",
        "alternative_uses": ["Model comparison", "Local API server", "Prompt experiments"],
        "download_url": "https://lmstudio.ai/",
        "homepage_url": "https://lmstudio.ai/",
        "icon": "MessageSquare",
        "popularity": 84,
        "platforms": ["Windows", "macOS", "Linux"],
    },
    {
        "name": "Cursor",
        "category_slug": "ai",
        "description": "AI-first IDE built on VS Code. Refactor, chat with codebase, generate fast.",
        "alternative_uses": ["Pair programming", "Code review", "Doc writing"],
        "download_url": "https://www.cursor.com/",
        "homepage_url": "https://www.cursor.com/",
        "icon": "Sparkles",
        "popularity": 92,
        "platforms": ["Windows", "macOS", "Linux"],
    },
    {
        "name": "Stable Diffusion WebUI",
        "category_slug": "ai",
        "description": "AUTOMATIC1111's web UI to run Stable Diffusion locally with thousands of extensions.",
        "alternative_uses": ["Inpainting", "ControlNet", "LoRA training"],
        "download_url": "https://github.com/AUTOMATIC1111/stable-diffusion-webui/releases",
        "homepage_url": "https://github.com/AUTOMATIC1111/stable-diffusion-webui",
        "icon": "ImagePlus",
        "popularity": 85,
        "is_open_source": True,
        "platforms": ["Windows", "macOS", "Linux"],
    },
    {
        "name": "ComfyUI",
        "category_slug": "ai",
        "description": "Powerful node-based GUI for Stable Diffusion. Build pipelines visually.",
        "alternative_uses": ["Video generation", "Custom workflows", "Batch jobs"],
        "download_url": "https://github.com/comfyanonymous/ComfyUI/releases",
        "homepage_url": "https://github.com/comfyanonymous/ComfyUI",
        "icon": "Network",
        "popularity": 80,
        "is_open_source": True,
        "platforms": ["Windows", "macOS", "Linux"],
    },
    {
        "name": "Anaconda",
        "category_slug": "ai",
        "description": "All-in-one Python distribution with conda, Jupyter and 250+ data-science packages.",
        "alternative_uses": ["Env management", "ML prototyping", "Teaching Python"],
        "download_url": "https://www.anaconda.com/download",
        "homepage_url": "https://www.anaconda.com/",
        "icon": "FlaskConical",
        "popularity": 78,
        "platforms": ["Windows", "macOS", "Linux"],
    },

    # ---------------- MEDIA ----------------
    {
        "name": "VLC Media Player",
        "category_slug": "media",
        "description": "Plays literally everything. The Swiss army knife of media players.",
        "alternative_uses": ["Stream conversion", "Disc ripping", "Screen recording"],
        "download_url": "https://www.videolan.org/vlc/",
        "homepage_url": "https://www.videolan.org/",
        "icon": "Play",
        "popularity": 97,
        "is_open_source": True,
        "platforms": ["Windows", "macOS", "Linux", "iOS", "Android"],
    },
    {
        "name": "OBS Studio",
        "category_slug": "media",
        "description": "Free, open-source screen recorder and live streaming software.",
        "alternative_uses": ["Twitch streaming", "Tutorial recording", "Webcam virtual cam"],
        "download_url": "https://obsproject.com/download",
        "homepage_url": "https://obsproject.com/",
        "icon": "Video",
        "popularity": 89,
        "is_open_source": True,
        "platforms": ["Windows", "macOS", "Linux"],
    },
    {
        "name": "HandBrake",
        "category_slug": "media",
        "description": "Open-source video transcoder. Converts almost any format into MP4/MKV.",
        "alternative_uses": ["Shrinking files", "Mobile-optimised exports", "DVD ripping"],
        "download_url": "https://handbrake.fr/downloads.php",
        "homepage_url": "https://handbrake.fr/",
        "icon": "FastForward",
        "popularity": 75,
        "is_open_source": True,
        "platforms": ["Windows", "macOS", "Linux"],
    },
    {
        "name": "Audacity",
        "category_slug": "media",
        "description": "Multi-track audio editor and recorder. Free & open source for 20+ years.",
        "alternative_uses": ["Podcast editing", "Noise removal", "Vinyl digitisation"],
        "download_url": "https://www.audacityteam.org/download/",
        "homepage_url": "https://www.audacityteam.org/",
        "icon": "AudioLines",
        "popularity": 82,
        "is_open_source": True,
        "platforms": ["Windows", "macOS", "Linux"],
    },
    {
        "name": "GIMP",
        "category_slug": "media",
        "description": "The GNU Image Manipulation Program — a free Photoshop alternative.",
        "alternative_uses": ["Photo editing", "Icon design", "Batch processing"],
        "download_url": "https://www.gimp.org/downloads/",
        "homepage_url": "https://www.gimp.org/",
        "icon": "Brush",
        "popularity": 84,
        "is_open_source": True,
        "platforms": ["Windows", "macOS", "Linux"],
    },
    {
        "name": "Krita",
        "category_slug": "media",
        "description": "Professional digital painting and illustration app loved by concept artists.",
        "alternative_uses": ["Animation", "Comic creation", "Texture painting"],
        "download_url": "https://krita.org/en/download/",
        "homepage_url": "https://krita.org/",
        "icon": "Palette",
        "popularity": 76,
        "is_open_source": True,
        "platforms": ["Windows", "macOS", "Linux"],
    },
    {
        "name": "FFmpeg",
        "category_slug": "media",
        "description": "The command-line tool that secretly powers half the internet's media pipelines.",
        "alternative_uses": ["Scripted conversions", "Streaming", "Filter graphs"],
        "download_url": "https://ffmpeg.org/download.html",
        "homepage_url": "https://ffmpeg.org/",
        "icon": "Film",
        "popularity": 93,
        "is_open_source": True,
        "platforms": ["Windows", "macOS", "Linux"],
    },
    {
        "name": "Inkscape",
        "category_slug": "media",
        "description": "Powerful, free SVG vector graphics editor.",
        "alternative_uses": ["Logo design", "Cricut/laser cutting", "Map making"],
        "download_url": "https://inkscape.org/release/",
        "homepage_url": "https://inkscape.org/",
        "icon": "PenTool",
        "popularity": 74,
        "is_open_source": True,
        "platforms": ["Windows", "macOS", "Linux"],
    },
    {
        "name": "Blender",
        "category_slug": "media",
        "description": "Free 3D creation suite: modeling, sculpting, animation, VFX and even video editing.",
        "alternative_uses": ["3D printing", "Game asset creation", "Architectural viz"],
        "download_url": "https://www.blender.org/download/",
        "homepage_url": "https://www.blender.org/",
        "icon": "Box",
        "popularity": 91,
        "is_open_source": True,
        "platforms": ["Windows", "macOS", "Linux"],
    },

    # ---------------- HARDWARE ----------------
    {
        "name": "CPU-Z",
        "category_slug": "hardware",
        "description": "Tells you exactly what's inside your PC: CPU, RAM, motherboard, GPU.",
        "alternative_uses": ["Overclocking", "Verifying parts", "Stress tests"],
        "download_url": "https://www.cpuid.com/softwares/cpu-z.html",
        "homepage_url": "https://www.cpuid.com/",
        "icon": "Cpu",
        "popularity": 85,
        "platforms": ["Windows"],
    },
    {
        "name": "HWMonitor",
        "category_slug": "hardware",
        "description": "Real-time temperatures, voltages and fan speeds for every sensor in your rig.",
        "alternative_uses": ["Thermal debugging", "Logging", "OC verification"],
        "download_url": "https://www.cpuid.com/softwares/hwmonitor.html",
        "homepage_url": "https://www.cpuid.com/",
        "icon": "Thermometer",
        "popularity": 78,
        "platforms": ["Windows"],
    },
    {
        "name": "CrystalDiskInfo",
        "category_slug": "hardware",
        "description": "Check the SMART health of your hard drives & SSDs before they die on you.",
        "alternative_uses": ["Used drive shopping", "Predictive failure", "TBW tracking"],
        "download_url": "https://crystalmark.info/en/download/",
        "homepage_url": "https://crystalmark.info/",
        "icon": "HardDrive",
        "popularity": 72,
        "is_open_source": True,
        "platforms": ["Windows"],
    },
    {
        "name": "MSI Afterburner",
        "category_slug": "hardware",
        "description": "The GPU tweaker. Overclock, undervolt, monitor and benchmark any card.",
        "alternative_uses": ["Fan curves", "On-screen FPS", "Recording gameplay"],
        "download_url": "https://www.msi.com/Landing/afterburner/graphics-cards",
        "homepage_url": "https://www.msi.com/",
        "icon": "Gauge",
        "popularity": 87,
        "platforms": ["Windows"],
    },
    {
        "name": "GPU-Z",
        "category_slug": "hardware",
        "description": "Tiny utility that shows everything about your graphics card. From TechPowerUp.",
        "alternative_uses": ["Buying second-hand GPUs", "Verifying BIOS", "Sensor logging"],
        "download_url": "https://www.techpowerup.com/gpuz/",
        "homepage_url": "https://www.techpowerup.com/",
        "icon": "MonitorCog",
        "popularity": 76,
        "platforms": ["Windows"],
    },
    {
        "name": "Speccy",
        "category_slug": "hardware",
        "description": "Clean, friendly system info app. Great for non-technical family tech support.",
        "alternative_uses": ["Inventory exports", "Old hardware audits", "Quick diagnostics"],
        "download_url": "https://www.ccleaner.com/speccy/download",
        "homepage_url": "https://www.ccleaner.com/speccy",
        "icon": "Info",
        "popularity": 60,
        "platforms": ["Windows"],
    },

    # ---------------- FUN ----------------
    {
        "name": "Cookie Clicker",
        "category_slug": "fun",
        "description": "Bake cookies. Buy grandmas. Ascend. The original idle game.",
        "alternative_uses": ["Wasting hours", "Tab-background meditation", "Studying RNG"],
        "download_url": "https://orteil.dashnet.org/cookieclicker/",
        "homepage_url": "https://orteil.dashnet.org/cookieclicker/",
        "icon": "Cookie",
        "popularity": 88,
        "platforms": ["Web"],
    },
    {
        "name": "Hacker Typer",
        "category_slug": "fun",
        "description": "Mash random keys, look like an elite hacker in green text on black. Classic.",
        "alternative_uses": ["Pranks", "Movie props", "Stress relief"],
        "download_url": "https://hackertyper.net/",
        "homepage_url": "https://hackertyper.net/",
        "icon": "TerminalSquare",
        "popularity": 71,
        "platforms": ["Web"],
    },
    {
        "name": "GeoFS",
        "category_slug": "fun",
        "description": "Free in-browser flight simulator using real satellite imagery. Just take off.",
        "alternative_uses": ["Procrastination", "Geography learning", "Multiplayer hangouts"],
        "download_url": "https://www.geo-fs.com/",
        "homepage_url": "https://www.geo-fs.com/",
        "icon": "Plane",
        "popularity": 64,
        "platforms": ["Web"],
    },
    {
        "name": "ASCII Art Generator (patorjk)",
        "category_slug": "fun",
        "description": "Type anything, pick a font, get instant ASCII art for your README / banner.",
        "alternative_uses": ["MOTD banners", "Email signatures", "Boredom"],
        "download_url": "https://patorjk.com/software/taag/",
        "homepage_url": "https://patorjk.com/",
        "icon": "Type",
        "popularity": 66,
        "platforms": ["Web"],
    },
    {
        "name": "The Useless Web",
        "category_slug": "fun",
        "description": "Hit a button. Be teleported to the weirdest corner of the internet.",
        "alternative_uses": ["Procrastination", "Mood booster", "Conversation starter"],
        "download_url": "https://theuselessweb.com/",
        "homepage_url": "https://theuselessweb.com/",
        "icon": "Shuffle",
        "popularity": 73,
        "platforms": ["Web"],
    },
    {
        "name": "Pointer Pointer",
        "category_slug": "fun",
        "description": "Move your mouse. Strangers will point at it. That's it. That's the site.",
        "alternative_uses": ["Existential crises", "Demo for friends", "Background art"],
        "download_url": "https://pointerpointer.com/",
        "homepage_url": "https://pointerpointer.com/",
        "icon": "MousePointer2",
        "popularity": 58,
        "platforms": ["Web"],
    },
    {
        "name": "Sandspiel",
        "category_slug": "fun",
        "description": "Mesmerizing falling-sand sandbox. Mix water, fire, plants, lava and watch.",
        "alternative_uses": ["Stress relief", "Teaching cellular automata", "Pixel art"],
        "download_url": "https://sandspiel.club/",
        "homepage_url": "https://sandspiel.club/",
        "icon": "Sparkle",
        "popularity": 62,
        "platforms": ["Web"],
    },
    {
        "name": "WindowSwap",
        "category_slug": "fun",
        "description": "Look out of someone else's window from somewhere in the world. Surprisingly calming.",
        "alternative_uses": ["Travel daydreaming", "Meditation", "Writing inspiration"],
        "download_url": "https://www.window-swap.com/",
        "homepage_url": "https://www.window-swap.com/",
        "icon": "Globe",
        "popularity": 55,
        "platforms": ["Web"],
    },
    {
        "name": "Bongo Cat",
        "category_slug": "fun",
        "description": "A cat that drums along to your keypresses. Inexplicably joyful.",
        "alternative_uses": ["Stream overlay", "ASMR", "Typing motivation"],
        "download_url": "https://bongo.cat/",
        "homepage_url": "https://bongo.cat/",
        "icon": "Cat",
        "popularity": 67,
        "platforms": ["Web"],
    },
    {
        "name": "neal.fun",
        "category_slug": "fun",
        "description": "A whole collection of weird, beautiful, addictive web experiments. Spend an hour.",
        "alternative_uses": ["Procrastination", "Sharing with friends", "Inspiration for devs"],
        "download_url": "https://neal.fun/",
        "homepage_url": "https://neal.fun/",
        "icon": "Rocket",
        "popularity": 79,
        "platforms": ["Web"],
    },

    # ================ EXTRA DEV ================
    {"name": "Neovim", "category_slug": "dev", "description": "Hyperextensible Vim-fork built for the modern era. Lua-scriptable, fast, terminal-native.", "alternative_uses": ["Note taking", "Markdown editing", "SSH dev"], "download_url": "https://github.com/neovim/neovim/releases", "homepage_url": "https://neovim.io/", "icon": "TerminalSquare", "popularity": 88, "is_open_source": True, "platforms": ["Windows", "macOS", "Linux"]},
    {"name": "GNU Emacs", "category_slug": "dev", "description": "Not a text editor — a Lisp machine that happens to edit text. The original IDE.", "alternative_uses": ["Org-mode planning", "Email", "Web browsing (eww)", "Therapy"], "download_url": "https://www.gnu.org/software/emacs/download.html", "homepage_url": "https://www.gnu.org/software/emacs/", "icon": "BookOpen", "popularity": 70, "is_open_source": True, "platforms": ["Windows", "macOS", "Linux"]},
    {"name": "Zed", "category_slug": "dev", "description": "Blazing-fast, multiplayer code editor written in Rust by the makers of Atom.", "alternative_uses": ["Pair programming", "Live coding", "Tree-sitter exploration"], "download_url": "https://zed.dev/download", "homepage_url": "https://zed.dev/", "icon": "Zap", "popularity": 78, "is_open_source": True, "platforms": ["macOS", "Linux"]},
    {"name": "Fork", "category_slug": "dev", "description": "Fast, friendly Git client with a beautiful UI. Free for personal use.", "alternative_uses": ["Branch visualization", "Conflict resolution", "Stash juggling"], "download_url": "https://git-fork.com/", "homepage_url": "https://git-fork.com/", "icon": "GitFork", "popularity": 71, "platforms": ["Windows", "macOS"]},
    {"name": "GitHub Desktop", "category_slug": "dev", "description": "Friendly Git client from GitHub. Great for visual learners and PR workflows.", "alternative_uses": ["Quick commits", "PR review", "Onboarding new devs"], "download_url": "https://desktop.github.com/", "homepage_url": "https://desktop.github.com/", "icon": "Github", "popularity": 74, "is_open_source": True, "platforms": ["Windows", "macOS"]},
    {"name": "Sourcetree", "category_slug": "dev", "description": "Free Mercurial & Git visual client by Atlassian.", "alternative_uses": ["Workflow visualization", "Submodule mgmt", "Hotfix planning"], "download_url": "https://www.sourcetreeapp.com/", "homepage_url": "https://www.sourcetreeapp.com/", "icon": "GitMerge", "popularity": 65, "platforms": ["Windows", "macOS"]},
    {"name": "TablePlus", "category_slug": "dev", "description": "Modern, native database GUI with a clean look and fast query editor.", "alternative_uses": ["Quick CSV imports", "Schema diff", "JSON viewing"], "download_url": "https://tableplus.com/download", "homepage_url": "https://tableplus.com/", "icon": "Table", "popularity": 73, "platforms": ["Windows", "macOS", "Linux"]},
    {"name": "Beekeeper Studio", "category_slug": "dev", "description": "Free, open-source SQL editor and database manager. Friendly UI, batteries included.", "alternative_uses": ["Cross-DB queries", "Backups", "Schema exploration"], "download_url": "https://www.beekeeperstudio.io/get", "homepage_url": "https://www.beekeeperstudio.io/", "icon": "Database", "popularity": 66, "is_open_source": True, "platforms": ["Windows", "macOS", "Linux"]},
    {"name": "Hoppscotch", "category_slug": "dev", "description": "Open-source API development ecosystem — the lightweight Postman alternative.", "alternative_uses": ["WebSocket testing", "MQTT debugging", "GraphQL playground"], "download_url": "https://hoppscotch.io/", "homepage_url": "https://hoppscotch.io/", "icon": "Send", "popularity": 70, "is_open_source": True, "platforms": ["Web", "Desktop"]},
    {"name": "Bun", "category_slug": "dev", "description": "All-in-one JS runtime & toolkit. Insanely fast bundler, test runner and package manager.", "alternative_uses": ["Replace npm+jest+webpack", "Edge functions", "TS scripts"], "download_url": "https://bun.sh/", "homepage_url": "https://bun.sh/", "icon": "Zap", "popularity": 83, "is_open_source": True, "platforms": ["Windows", "macOS", "Linux"]},
    {"name": "Deno", "category_slug": "dev", "description": "Secure JavaScript & TypeScript runtime built on V8 and Rust.", "alternative_uses": ["Single-file scripts", "Edge compute", "Native TS"], "download_url": "https://deno.com/", "homepage_url": "https://deno.com/", "icon": "Triangle", "popularity": 75, "is_open_source": True, "platforms": ["Windows", "macOS", "Linux"]},
    {"name": "pnpm", "category_slug": "dev", "description": "Fast, disk-efficient package manager that uses a content-addressable store.", "alternative_uses": ["Monorepo workspaces", "CI caching", "Disk space savings"], "download_url": "https://pnpm.io/installation", "homepage_url": "https://pnpm.io/", "icon": "Package", "popularity": 79, "is_open_source": True, "platforms": ["Windows", "macOS", "Linux"]},
    {"name": "jq", "category_slug": "dev", "description": "The 'sed' of JSON. Slice, filter, map and transform structured data on the CLI.", "alternative_uses": ["API response parsing", "Bash scripting", "Log filtering"], "download_url": "https://jqlang.org/download/", "homepage_url": "https://jqlang.github.io/jq/", "icon": "Braces", "popularity": 81, "is_open_source": True, "platforms": ["Windows", "macOS", "Linux"]},
    {"name": "GitHub CLI (gh)", "category_slug": "dev", "description": "GitHub on the command line. PRs, issues, releases, gists — without leaving your shell.", "alternative_uses": ["Scripting workflows", "Triage from terminal", "CI on dev box"], "download_url": "https://cli.github.com/", "homepage_url": "https://cli.github.com/", "icon": "Github", "popularity": 84, "is_open_source": True, "platforms": ["Windows", "macOS", "Linux"]},
    {"name": "MongoDB Compass", "category_slug": "dev", "description": "The official GUI for MongoDB. Explore data, build queries and analyze performance.", "alternative_uses": ["Schema analysis", "Index suggestion", "Aggregation builder"], "download_url": "https://www.mongodb.com/products/compass", "homepage_url": "https://www.mongodb.com/products/compass", "icon": "Leaf", "popularity": 72, "platforms": ["Windows", "macOS", "Linux"]},
    {"name": "Redis Insight", "category_slug": "dev", "description": "Visual tool for designing, developing and optimizing Redis applications.", "alternative_uses": ["Stream debugging", "Memory analysis", "Slow log review"], "download_url": "https://redis.io/insight/", "homepage_url": "https://redis.io/insight/", "icon": "Activity", "popularity": 67, "platforms": ["Windows", "macOS", "Linux"]},
    {"name": "Rust", "category_slug": "dev", "description": "Systems language with memory safety, zero-cost abstractions and a famously helpful compiler.", "alternative_uses": ["CLI tools", "Web backends", "Embedded", "WASM"], "download_url": "https://www.rust-lang.org/tools/install", "homepage_url": "https://www.rust-lang.org/", "icon": "Cog", "popularity": 90, "is_open_source": True, "platforms": ["Windows", "macOS", "Linux"]},
    {"name": "Go", "category_slug": "dev", "description": "Simple, statically-typed compiled language designed at Google. Killer concurrency story.", "alternative_uses": ["Microservices", "DevOps tools", "Network daemons"], "download_url": "https://go.dev/dl/", "homepage_url": "https://go.dev/", "icon": "Sailboat", "popularity": 88, "is_open_source": True, "platforms": ["Windows", "macOS", "Linux"]},

    # ================ EXTRA NETWORK ================
    {"name": "WireGuard", "category_slug": "network", "description": "Modern, fast, simple VPN. Tiny attack surface, audited, easy to configure.", "alternative_uses": ["Self-hosted VPN", "Site-to-site", "Mobile-friendly tunnels"], "download_url": "https://www.wireguard.com/install/", "homepage_url": "https://www.wireguard.com/", "icon": "Shield", "popularity": 86, "is_open_source": True, "platforms": ["Windows", "macOS", "Linux", "iOS", "Android"]},
    {"name": "Tailscale", "category_slug": "network", "description": "Zero-config mesh VPN built on WireGuard. Your devices on a private network in 30 seconds.", "alternative_uses": ["Remote work", "Self-hosted services", "Cross-OS file sharing"], "download_url": "https://tailscale.com/download", "homepage_url": "https://tailscale.com/", "icon": "Network", "popularity": 89, "platforms": ["Windows", "macOS", "Linux", "iOS", "Android"]},
    {"name": "ZeroTier", "category_slug": "network", "description": "Smart Ethernet switch in the cloud. Create global virtual networks with ease.", "alternative_uses": ["Gaming LAN parties", "IoT meshes", "Remote labs"], "download_url": "https://www.zerotier.com/download/", "homepage_url": "https://www.zerotier.com/", "icon": "Globe", "popularity": 70, "is_open_source": True, "platforms": ["Windows", "macOS", "Linux", "iOS", "Android"]},
    {"name": "Pi-hole", "category_slug": "network", "description": "Network-wide ad blocker that runs on a Raspberry Pi (or any Linux box).", "alternative_uses": ["DNS sinkhole", "Telemetry blocking", "Family-safe internet"], "download_url": "https://pi-hole.net/", "homepage_url": "https://pi-hole.net/", "icon": "Shield", "popularity": 84, "is_open_source": True, "platforms": ["Linux", "Docker", "RPi"]},
    {"name": "AdGuard Home", "category_slug": "network", "description": "Self-hosted network-wide ad & tracker blocker with a slick web UI.", "alternative_uses": ["Parental controls", "DNS-over-TLS", "Privacy dashboards"], "download_url": "https://adguard.com/en/adguard-home/overview.html", "homepage_url": "https://adguard.com/", "icon": "ShieldCheck", "popularity": 76, "is_open_source": True, "platforms": ["Windows", "macOS", "Linux"]},
    {"name": "iperf3", "category_slug": "network", "description": "Active measurement tool for the maximum achievable bandwidth on IP networks.", "alternative_uses": ["LAN benchmarking", "VPN throughput", "ISP debugging"], "download_url": "https://iperf.fr/iperf-download.php", "homepage_url": "https://iperf.fr/", "icon": "Gauge", "popularity": 73, "is_open_source": True, "platforms": ["Windows", "macOS", "Linux"]},
    {"name": "Speedtest CLI", "category_slug": "network", "description": "Official Speedtest by Ookla, but in the terminal. Perfect for scripting and CI.", "alternative_uses": ["Cron health checks", "ISP shaming", "RPi monitoring"], "download_url": "https://www.speedtest.net/apps/cli", "homepage_url": "https://www.speedtest.net/", "icon": "Activity", "popularity": 68, "platforms": ["Windows", "macOS", "Linux"]},
    {"name": "Termius", "category_slug": "network", "description": "Modern, cross-platform SSH client with sync, snippets and a beautiful UI.", "alternative_uses": ["Mobile server admin", "Team key sharing", "Port forwarding"], "download_url": "https://termius.com/download", "homepage_url": "https://termius.com/", "icon": "Terminal", "popularity": 70, "platforms": ["Windows", "macOS", "Linux", "iOS", "Android"]},
    {"name": "Fing", "category_slug": "network", "description": "Find every device on your Wi-Fi in seconds. Hunt for the device hogging bandwidth.", "alternative_uses": ["Rogue device detection", "Speed tests", "Wi-Fi auditing"], "download_url": "https://www.fing.com/products/fing-desktop", "homepage_url": "https://www.fing.com/", "icon": "Wifi", "popularity": 64, "platforms": ["Windows", "macOS", "iOS", "Android"]},
    {"name": "Mullvad VPN", "category_slug": "network", "description": "Privacy-respecting VPN that doesn't even want your email. Pay in cash if you like.", "alternative_uses": ["Anonymous research", "Travel privacy", "Streaming bypass"], "download_url": "https://mullvad.net/en/download", "homepage_url": "https://mullvad.net/", "icon": "EyeOff", "popularity": 78, "is_open_source": True, "platforms": ["Windows", "macOS", "Linux", "iOS", "Android"]},

    # ================ EXTRA SECURITY ================
    {"name": "John the Ripper", "category_slug": "security", "description": "Legendary password cracker. Tests password strength against many hash formats.", "alternative_uses": ["Forensics", "CTFs", "Self-audit weak passwords"], "download_url": "https://www.openwall.com/john/", "homepage_url": "https://www.openwall.com/john/", "icon": "KeyRound", "popularity": 72, "is_open_source": True, "platforms": ["Windows", "macOS", "Linux"]},
    {"name": "Hashcat", "category_slug": "security", "description": "World's fastest password recovery tool with GPU acceleration.", "alternative_uses": ["Password audits", "Recovery of own forgotten passwords", "CTF"], "download_url": "https://hashcat.net/hashcat/", "homepage_url": "https://hashcat.net/", "icon": "Cpu", "popularity": 78, "is_open_source": True, "platforms": ["Windows", "macOS", "Linux"]},
    {"name": "Aircrack-ng", "category_slug": "security", "description": "Suite of Wi-Fi security tools: monitor, attack, test and crack.", "alternative_uses": ["Wi-Fi auditing", "Packet capture", "Learning 802.11"], "download_url": "https://www.aircrack-ng.org/downloads.html", "homepage_url": "https://www.aircrack-ng.org/", "icon": "Wifi", "popularity": 76, "is_open_source": True, "platforms": ["Windows", "Linux"]},
    {"name": "OWASP ZAP", "category_slug": "security", "description": "Free, open-source web app security scanner from OWASP.", "alternative_uses": ["DAST", "Spidering", "Fuzzing"], "download_url": "https://www.zaproxy.org/download/", "homepage_url": "https://www.zaproxy.org/", "icon": "ShieldAlert", "popularity": 74, "is_open_source": True, "platforms": ["Windows", "macOS", "Linux"]},
    {"name": "ClamAV", "category_slug": "security", "description": "Open-source antivirus engine. Used in mail gateways, file scanners and more.", "alternative_uses": ["Mail server scanning", "Download scanning", "CI artifact scans"], "download_url": "https://www.clamav.net/downloads", "homepage_url": "https://www.clamav.net/", "icon": "Bug", "popularity": 65, "is_open_source": True, "platforms": ["Windows", "macOS", "Linux"]},
    {"name": "ProtonVPN", "category_slug": "security", "description": "From the makers of Proton Mail. Strong privacy, audited, free tier exists.", "alternative_uses": ["Travel encryption", "Streaming geo-shift", "Censorship bypass"], "download_url": "https://protonvpn.com/download", "homepage_url": "https://protonvpn.com/", "icon": "Shield", "popularity": 77, "platforms": ["Windows", "macOS", "Linux", "iOS", "Android"]},
    {"name": "Signal", "category_slug": "security", "description": "End-to-end encrypted messenger that doesn't sell your data. The gold standard.", "alternative_uses": ["Confidential chats", "Disappearing messages", "Encrypted calls"], "download_url": "https://signal.org/download/", "homepage_url": "https://signal.org/", "icon": "MessageCircle", "popularity": 89, "is_open_source": True, "platforms": ["Windows", "macOS", "Linux", "iOS", "Android"]},
    {"name": "Have I Been Pwned (Notify)", "category_slug": "security", "description": "Check if your email or password leaked in a breach. Free notifications, too.", "alternative_uses": ["Breach monitoring", "Password reuse audits", "Family digital hygiene"], "download_url": "https://haveibeenpwned.com/", "homepage_url": "https://haveibeenpwned.com/", "icon": "AlertTriangle", "popularity": 81, "platforms": ["Web"]},
    {"name": "Cryptomator", "category_slug": "security", "description": "Multi-platform transparent client-side encryption for your cloud files.", "alternative_uses": ["Encrypt Dropbox/Drive", "Local vaults", "Cross-OS access"], "download_url": "https://cryptomator.org/downloads/", "homepage_url": "https://cryptomator.org/", "icon": "Lock", "popularity": 69, "is_open_source": True, "platforms": ["Windows", "macOS", "Linux", "iOS", "Android"]},
    {"name": "GnuPG", "category_slug": "security", "description": "OpenPGP-compatible encryption and signing. The 'gpg' command you've seen for decades.", "alternative_uses": ["Email encryption", "Signing git commits", "Distributing checksums"], "download_url": "https://gnupg.org/download/", "homepage_url": "https://gnupg.org/", "icon": "KeySquare", "popularity": 71, "is_open_source": True, "platforms": ["Windows", "macOS", "Linux"]},

    # ================ EXTRA OS ================
    {"name": "Chocolatey", "category_slug": "os", "description": "The package manager for Windows. Install software via a single CLI command.", "alternative_uses": ["Automated provisioning", "Updates", "Dotfile bootstrapping"], "download_url": "https://chocolatey.org/install", "homepage_url": "https://chocolatey.org/", "icon": "Package", "popularity": 75, "is_open_source": True, "platforms": ["Windows"]},
    {"name": "Scoop", "category_slug": "os", "description": "Command-line installer for Windows. Installs to your user dir, no UAC prompts.", "alternative_uses": ["Dev environment setup", "Portable installs", "Quick rollbacks"], "download_url": "https://scoop.sh/", "homepage_url": "https://scoop.sh/", "icon": "Spade", "popularity": 70, "is_open_source": True, "platforms": ["Windows"]},
    {"name": "Homebrew", "category_slug": "os", "description": "The missing package manager for macOS (and Linux). 'brew install' literally anything.", "alternative_uses": ["Casks (GUI apps)", "Service mgmt", "Dotfiles"], "download_url": "https://brew.sh/", "homepage_url": "https://brew.sh/", "icon": "Beer", "popularity": 95, "is_open_source": True, "platforms": ["macOS", "Linux"]},
    {"name": "WSL", "category_slug": "os", "description": "Windows Subsystem for Linux. Full Ubuntu/Debian/etc kernel running under Windows.", "alternative_uses": ["Linux dev on Windows", "Docker backend", "Server scripting"], "download_url": "https://learn.microsoft.com/en-us/windows/wsl/install", "homepage_url": "https://learn.microsoft.com/en-us/windows/wsl/", "icon": "TerminalSquare", "popularity": 88, "platforms": ["Windows"]},
    {"name": "WizTree", "category_slug": "os", "description": "Insanely fast disk space analyzer. Reads the MFT directly.", "alternative_uses": ["Find huge files", "Old downloads cleanup", "Drive forensics"], "download_url": "https://diskanalyzer.com/download", "homepage_url": "https://diskanalyzer.com/", "icon": "PieChart", "popularity": 72, "platforms": ["Windows"]},
    {"name": "ShareX", "category_slug": "os", "description": "Free screen capture/recording with built-in OCR, GIF maker and upload destinations.", "alternative_uses": ["Quick tutorials", "Annotated bug reports", "Color picker"], "download_url": "https://getsharex.com/downloads", "homepage_url": "https://getsharex.com/", "icon": "Camera", "popularity": 82, "is_open_source": True, "platforms": ["Windows"]},
    {"name": "Flameshot", "category_slug": "os", "description": "Powerful, easy-to-use screenshot tool with on-screen annotation. Loved on Linux.", "alternative_uses": ["Annotated screenshots", "Imgur upload", "Quick redactions"], "download_url": "https://flameshot.org/", "homepage_url": "https://flameshot.org/", "icon": "Crop", "popularity": 70, "is_open_source": True, "platforms": ["Windows", "macOS", "Linux"]},
    {"name": "f.lux", "category_slug": "os", "description": "Makes your screen adapt to the time of day. Warm at night, full white at day.", "alternative_uses": ["Eye strain reduction", "Sleep-cycle hygiene", "Late-night coding"], "download_url": "https://justgetflux.com/", "homepage_url": "https://justgetflux.com/", "icon": "SunMoon", "popularity": 68, "platforms": ["Windows", "macOS", "Linux"]},
    {"name": "Alfred", "category_slug": "os", "description": "macOS productivity app: launch apps, search files, run workflows. The Mac power user's secret.", "alternative_uses": ["Clipboard history", "Snippets", "Custom workflows"], "download_url": "https://www.alfredapp.com/", "homepage_url": "https://www.alfredapp.com/", "icon": "Hat", "popularity": 76, "platforms": ["macOS"]},
    {"name": "Raycast", "category_slug": "os", "description": "Lightning-fast launcher for macOS (and now Windows). Extensions, AI, snippets.", "alternative_uses": ["Window management", "Spotlight replacement", "AI prompts"], "download_url": "https://www.raycast.com/", "homepage_url": "https://www.raycast.com/", "icon": "Rocket", "popularity": 84, "platforms": ["macOS", "Windows"]},

    # ================ EXTRA AI ================
    {"name": "Continue.dev", "category_slug": "ai", "description": "Open-source autopilot extension for VS Code and JetBrains. Bring your own model.", "alternative_uses": ["Refactor in IDE", "Code Q&A", "Test gen"], "download_url": "https://www.continue.dev/", "homepage_url": "https://www.continue.dev/", "icon": "Sparkles", "popularity": 76, "is_open_source": True, "platforms": ["Windows", "macOS", "Linux"]},
    {"name": "Aider", "category_slug": "ai", "description": "AI pair programmer in your terminal. Edits your git repo directly via chat.", "alternative_uses": ["Repo-wide refactor", "Test generation", "Doc writing"], "download_url": "https://aider.chat/", "homepage_url": "https://aider.chat/", "icon": "Bot", "popularity": 78, "is_open_source": True, "platforms": ["Windows", "macOS", "Linux"]},
    {"name": "Open WebUI", "category_slug": "ai", "description": "Beautiful self-hosted web UI for Ollama and any OpenAI-compatible API.", "alternative_uses": ["Team LLM portal", "RAG over docs", "Multi-model compare"], "download_url": "https://docs.openwebui.com/", "homepage_url": "https://openwebui.com/", "icon": "MessageSquare", "popularity": 80, "is_open_source": True, "platforms": ["Docker", "Windows", "macOS", "Linux"]},
    {"name": "Jan", "category_slug": "ai", "description": "Privacy-first open-source ChatGPT alternative that runs 100% offline on your machine.", "alternative_uses": ["Offline assistants", "API server", "Model marketplace"], "download_url": "https://jan.ai/download", "homepage_url": "https://jan.ai/", "icon": "Brain", "popularity": 73, "is_open_source": True, "platforms": ["Windows", "macOS", "Linux"]},
    {"name": "Pinokio", "category_slug": "ai", "description": "Browser for AI: install and launch dozens of AI apps with one click.", "alternative_uses": ["SD WebUI install", "Audio AI", "Video gen"], "download_url": "https://pinokio.computer/", "homepage_url": "https://pinokio.computer/", "icon": "AppWindow", "popularity": 67, "platforms": ["Windows", "macOS", "Linux"]},
    {"name": "DiffusionBee", "category_slug": "ai", "description": "Easiest way to run Stable Diffusion on Mac. Native, drag-drop, no terminal.", "alternative_uses": ["Concept art", "Avatar generation", "Inpainting on Mac"], "download_url": "https://diffusionbee.com/", "homepage_url": "https://diffusionbee.com/", "icon": "ImagePlus", "popularity": 70, "platforms": ["macOS"]},
    {"name": "Whisper", "category_slug": "ai", "description": "OpenAI's open-source speech-to-text model. Insanely accurate for free.", "alternative_uses": ["Podcast transcription", "Meeting notes", "Subtitles"], "download_url": "https://github.com/openai/whisper", "homepage_url": "https://openai.com/research/whisper", "icon": "Mic", "popularity": 86, "is_open_source": True, "platforms": ["Windows", "macOS", "Linux"]},
    {"name": "Faraday", "category_slug": "ai", "description": "Offline character AI on your desktop. Roleplay, write, brainstorm — fully local.", "alternative_uses": ["Creative writing", "Tabletop NPCs", "Co-author fiction"], "download_url": "https://faraday.dev/", "homepage_url": "https://faraday.dev/", "icon": "Drama", "popularity": 65, "platforms": ["Windows", "macOS", "Linux"]},

    # ================ EXTRA MEDIA ================
    {"name": "DaVinci Resolve", "category_slug": "media", "description": "Hollywood-grade video editor and color grader. The free version is absurdly good.", "alternative_uses": ["YouTube editing", "Color grading", "Motion graphics", "Audio post"], "download_url": "https://www.blackmagicdesign.com/products/davinciresolve", "homepage_url": "https://www.blackmagicdesign.com/products/davinciresolve", "icon": "Clapperboard", "popularity": 87, "platforms": ["Windows", "macOS", "Linux"]},
    {"name": "Kdenlive", "category_slug": "media", "description": "Free and open-source video editor with multi-track timeline.", "alternative_uses": ["YouTube content", "Documentary editing", "Tutorials"], "download_url": "https://kdenlive.org/en/download/", "homepage_url": "https://kdenlive.org/", "icon": "Film", "popularity": 70, "is_open_source": True, "platforms": ["Windows", "macOS", "Linux"]},
    {"name": "IrfanView", "category_slug": "media", "description": "Tiny, fast image viewer for Windows. Batch convert, basic edits, EVERY format.", "alternative_uses": ["Batch resizing", "RAW preview", "Slideshow"], "download_url": "https://www.irfanview.com/", "homepage_url": "https://www.irfanview.com/", "icon": "Image", "popularity": 74, "platforms": ["Windows"]},
    {"name": "REAPER", "category_slug": "media", "description": "Pro-grade DAW that's tiny, cheap and infinitely customizable.", "alternative_uses": ["Podcast editing", "Music production", "Field recording"], "download_url": "https://www.reaper.fm/download.php", "homepage_url": "https://www.reaper.fm/", "icon": "Music", "popularity": 73, "platforms": ["Windows", "macOS", "Linux"]},
    {"name": "Mixxx", "category_slug": "media", "description": "Free, open-source DJ software with everything pros need.", "alternative_uses": ["Live mixing", "DJ practice", "MIDI controllers"], "download_url": "https://mixxx.org/download/", "homepage_url": "https://mixxx.org/", "icon": "Disc3", "popularity": 60, "is_open_source": True, "platforms": ["Windows", "macOS", "Linux"]},
    {"name": "yt-dlp", "category_slug": "media", "description": "Feature-rich youtube-dl fork that downloads from 1000+ sites.", "alternative_uses": ["Podcast archiving", "Educational video offline", "Audio extraction"], "download_url": "https://github.com/yt-dlp/yt-dlp/releases", "homepage_url": "https://github.com/yt-dlp/yt-dlp", "icon": "DownloadCloud", "popularity": 88, "is_open_source": True, "platforms": ["Windows", "macOS", "Linux"]},
    {"name": "Olive", "category_slug": "media", "description": "Free open-source non-linear video editor. Promising, modern UI.", "alternative_uses": ["Indie editing", "Cross-platform projects", "Learning NLE"], "download_url": "https://www.olivevideoeditor.org/download.php", "homepage_url": "https://www.olivevideoeditor.org/", "icon": "PlaySquare", "popularity": 55, "is_open_source": True, "platforms": ["Windows", "macOS", "Linux"]},

    # ================ EXTRA HARDWARE ================
    {"name": "Memtest86", "category_slug": "hardware", "description": "Standalone memory testing software. Boot from USB and find bad RAM.", "alternative_uses": ["Diagnose BSODs", "Verify OC stability", "Pre-build burn-in"], "download_url": "https://www.memtest86.com/download.htm", "homepage_url": "https://www.memtest86.com/", "icon": "MemoryStick", "popularity": 78, "platforms": ["BIOS/UEFI"]},
    {"name": "Cinebench", "category_slug": "hardware", "description": "Real-world CPU benchmark based on Cinema 4D. The de facto standard.", "alternative_uses": ["Comparing CPUs", "OC validation", "Reviewing builds"], "download_url": "https://www.maxon.net/en/cinebench", "homepage_url": "https://www.maxon.net/en/cinebench", "icon": "Gauge", "popularity": 80, "platforms": ["Windows", "macOS"]},
    {"name": "FurMark", "category_slug": "hardware", "description": "GPU stress test and benchmark. The classic 'furry donut' burner.", "alternative_uses": ["Thermal stress", "PSU stability", "Cooling validation"], "download_url": "https://geeks3d.com/furmark/", "homepage_url": "https://geeks3d.com/furmark/", "icon": "Flame", "popularity": 72, "platforms": ["Windows"]},
    {"name": "HWiNFO", "category_slug": "hardware", "description": "Insanely detailed system info & sensor monitor. The pro choice.", "alternative_uses": ["Sensor logging", "Real-time monitoring", "Reviewing builds"], "download_url": "https://www.hwinfo.com/download/", "homepage_url": "https://www.hwinfo.com/", "icon": "Activity", "popularity": 79, "platforms": ["Windows"]},
    {"name": "ThrottleStop", "category_slug": "hardware", "description": "Tame thermal throttling on Intel laptops. Undervolt, tweak power limits.", "alternative_uses": ["Laptop tuning", "Battery life", "Gaming on thin laptops"], "download_url": "https://www.techpowerup.com/download/techpowerup-throttlestop/", "homepage_url": "https://www.techpowerup.com/download/techpowerup-throttlestop/", "icon": "Gauge", "popularity": 64, "platforms": ["Windows"]},
    {"name": "AIDA64 Extreme", "category_slug": "hardware", "description": "Comprehensive system diagnostics, benchmarks and stress tests.", "alternative_uses": ["Hardware inventory", "Stability testing", "Detailed reports"], "download_url": "https://www.aida64.com/downloads", "homepage_url": "https://www.aida64.com/", "icon": "Cog", "popularity": 70, "platforms": ["Windows"]},

    # ================ EXTRA FUN ================
    {"name": "ZType", "category_slug": "fun", "description": "Shoot space invaders by typing words. Surprisingly great for improving WPM.", "alternative_uses": ["Typing practice", "Coffee-break game", "Office competition"], "download_url": "https://zty.pe/", "homepage_url": "https://zty.pe/", "icon": "Keyboard", "popularity": 65, "platforms": ["Web"]},
    {"name": "Staggering Beauty", "category_slug": "fun", "description": "A worm. Don't shake it. (Photosensitive warning.)", "alternative_uses": ["Pranking friends", "Surreal art", "Quick laugh"], "download_url": "https://staggeringbeauty.com/", "homepage_url": "https://staggeringbeauty.com/", "icon": "Worm", "popularity": 54, "platforms": ["Web"]},
    {"name": "Patatap", "category_slug": "fun", "description": "Tap your keyboard. Music and shapes happen. Endlessly delightful.", "alternative_uses": ["Stress relief", "Music improvisation", "Kid distraction"], "download_url": "https://patatap.com/", "homepage_url": "https://patatap.com/", "icon": "Music4", "popularity": 60, "platforms": ["Web"]},
    {"name": "Quick, Draw!", "category_slug": "fun", "description": "Google's neural net guesses what you're sketching in under 20 seconds.", "alternative_uses": ["Doodling practice", "Family game", "ML education"], "download_url": "https://quickdraw.withgoogle.com/", "homepage_url": "https://quickdraw.withgoogle.com/", "icon": "PencilLine", "popularity": 68, "platforms": ["Web"]},
    {"name": "One Million Checkboxes", "category_slug": "fun", "description": "A page with a million checkboxes. Everyone can toggle them. Watching it move is hypnotic.", "alternative_uses": ["Mass-coordination experiments", "Internet sociology", "Time-wasting"], "download_url": "https://onemillioncheckboxes.com/", "homepage_url": "https://onemillioncheckboxes.com/", "icon": "CheckSquare", "popularity": 58, "platforms": ["Web"]},
    {"name": "A Dark Room", "category_slug": "fun", "description": "Minimalist text-based clicker that becomes a sprawling sci-fi adventure.", "alternative_uses": ["Background gameplay", "Storytelling inspiration", "Idle progress"], "download_url": "https://adarkroom.doublespeakgames.com/", "homepage_url": "https://adarkroom.doublespeakgames.com/", "icon": "Moon", "popularity": 62, "platforms": ["Web"]},
    {"name": "Don't Shoot The Puppy", "category_slug": "fun", "description": "The objective: do nothing. A philosophy lesson disguised as a meme.", "alternative_uses": ["Existential reflection", "Patience training", "Demos at parties"], "download_url": "https://dontshootthepuppy.com/", "homepage_url": "https://dontshootthepuppy.com/", "icon": "Dog", "popularity": 50, "platforms": ["Web"]},
    {"name": "Drawing Garden (silk.com)", "category_slug": "fun", "description": "Generates symmetrical, silky art as you drag your cursor. Meditative.", "alternative_uses": ["Background art", "Mindfulness", "Wallpaper creation"], "download_url": "https://weavesilk.com/", "homepage_url": "https://weavesilk.com/", "icon": "Sparkles", "popularity": 64, "platforms": ["Web"]},
    {"name": "Internet Roadtrip", "category_slug": "fun", "description": "A continent-spanning Street View road trip everyone watches together.", "alternative_uses": ["Geographic curiosity", "Background ambience", "Multiplayer mood"], "download_url": "https://neal.fun/internet-roadtrip/", "homepage_url": "https://neal.fun/internet-roadtrip/", "icon": "Car", "popularity": 66, "platforms": ["Web"]},
    {"name": "Falling Sand Game (classic)", "category_slug": "fun", "description": "OG falling-sand toy. Combine sand, water, plant, fire, virus, lava…", "alternative_uses": ["Teaching cellular automata", "Drawing physics", "Pure procrastination"], "download_url": "https://thefallingsandgame.com/", "homepage_url": "https://thefallingsandgame.com/", "icon": "Hourglass", "popularity": 60, "platforms": ["Web"]},

    # ================ COMMUNICATION ================
    {"name": "Discord", "category_slug": "comm", "description": "Voice, video, and text chat for communities, friends and game lobbies.", "alternative_uses": ["Study groups", "Game LFG", "Server hosting"], "download_url": "https://discord.com/download", "homepage_url": "https://discord.com/", "icon": "MessageSquare", "popularity": 95, "platforms": ["Windows", "macOS", "Linux", "iOS", "Android"]},
    {"name": "Element (Matrix)", "category_slug": "comm", "description": "Federated, end-to-end encrypted chat on the open Matrix protocol.", "alternative_uses": ["Decentralized teams", "Bridging Slack/Discord", "Sovereign chat"], "download_url": "https://element.io/download", "homepage_url": "https://element.io/", "icon": "Atom", "popularity": 70, "is_open_source": True, "platforms": ["Windows", "macOS", "Linux", "iOS", "Android"]},
    {"name": "Telegram", "category_slug": "comm", "description": "Fast, cloud-based messenger with big groups, channels and bots.", "alternative_uses": ["Backup chats anywhere", "File transfer (4GB!)", "Bot platforms"], "download_url": "https://telegram.org/apps", "homepage_url": "https://telegram.org/", "icon": "Send", "popularity": 88, "platforms": ["Windows", "macOS", "Linux", "iOS", "Android"]},
    {"name": "Slack", "category_slug": "comm", "description": "Team chat that ate enterprise communication.", "alternative_uses": ["Project channels", "ChatOps", "DevOps alerts"], "download_url": "https://slack.com/downloads", "homepage_url": "https://slack.com/", "icon": "Hash", "popularity": 86, "platforms": ["Windows", "macOS", "Linux", "iOS", "Android"]},
    {"name": "Mumble", "category_slug": "comm", "description": "Low-latency open-source voice chat for gamers and devs.", "alternative_uses": ["Self-hosted voice", "Radio nets", "VR voice"], "download_url": "https://www.mumble.info/downloads/", "homepage_url": "https://www.mumble.info/", "icon": "Mic", "popularity": 55, "is_open_source": True, "platforms": ["Windows", "macOS", "Linux"]},
    {"name": "Jitsi Meet", "category_slug": "comm", "description": "Open-source, browser-based video conferencing. No account needed.", "alternative_uses": ["Quick meetings", "Self-hosted Zoom", "End-to-end calls"], "download_url": "https://meet.jit.si/", "homepage_url": "https://jitsi.org/", "icon": "Video", "popularity": 68, "is_open_source": True, "platforms": ["Web", "Windows", "macOS", "Linux"]},
    {"name": "HexChat", "category_slug": "comm", "description": "Free, open-source IRC client for the nostalgia and the still-active networks.", "alternative_uses": ["Libera Chat", "Open-source dev rooms", "Retro vibes"], "download_url": "https://hexchat.github.io/downloads.html", "homepage_url": "https://hexchat.github.io/", "icon": "Hash", "popularity": 50, "is_open_source": True, "platforms": ["Windows", "Linux"]},
    {"name": "Revolt", "category_slug": "comm", "description": "Open-source chat platform that looks suspiciously like a certain other one.", "alternative_uses": ["Self-hosted server", "Community chat", "Discord alt"], "download_url": "https://revolt.chat/download", "homepage_url": "https://revolt.chat/", "icon": "MessagesSquare", "popularity": 58, "is_open_source": True, "platforms": ["Windows", "macOS", "Linux", "Web"]},

    # ================ PRODUCTIVITY ================
    {"name": "Obsidian", "category_slug": "prod", "description": "Local-first knowledge base on plain markdown files. Graph view + 1000 plugins.", "alternative_uses": ["Second brain", "PARA / Zettelkasten", "Daily journaling"], "download_url": "https://obsidian.md/download", "homepage_url": "https://obsidian.md/", "icon": "Brain", "popularity": 92, "platforms": ["Windows", "macOS", "Linux", "iOS", "Android"]},
    {"name": "Logseq", "category_slug": "prod", "description": "Outliner-style knowledge graph, open-source, local-first.", "alternative_uses": ["Daily notes", "Spaced repetition", "Linked thought"], "download_url": "https://logseq.com/downloads", "homepage_url": "https://logseq.com/", "icon": "Network", "popularity": 74, "is_open_source": True, "platforms": ["Windows", "macOS", "Linux"]},
    {"name": "Joplin", "category_slug": "prod", "description": "Open-source note-taking & to-do app with end-to-end encryption.", "alternative_uses": ["Self-hosted sync", "Encrypted journaling", "Markdown clipper"], "download_url": "https://joplinapp.org/download/", "homepage_url": "https://joplinapp.org/", "icon": "NotebookPen", "popularity": 72, "is_open_source": True, "platforms": ["Windows", "macOS", "Linux", "iOS", "Android"]},
    {"name": "Anki", "category_slug": "prod", "description": "Spaced repetition flashcards used by med students, polyglots & geeks alike.", "alternative_uses": ["Vocab learning", "Med school", "Code syntax memorization"], "download_url": "https://apps.ankiweb.net/", "homepage_url": "https://apps.ankiweb.net/", "icon": "Layers", "popularity": 87, "is_open_source": True, "platforms": ["Windows", "macOS", "Linux", "iOS", "Android"]},
    {"name": "Excalidraw", "category_slug": "prod", "description": "Whiteboard with a hand-drawn feel for sketching diagrams collaboratively.", "alternative_uses": ["Architecture diagrams", "Brainstorming", "Whiteboard interviews"], "download_url": "https://excalidraw.com/", "homepage_url": "https://excalidraw.com/", "icon": "PenTool", "popularity": 84, "is_open_source": True, "platforms": ["Web"]},
    {"name": "draw.io / diagrams.net", "category_slug": "prod", "description": "Free flowchart & diagram tool with desktop apps and offline support.", "alternative_uses": ["UML", "Network topology", "Process maps"], "download_url": "https://www.drawio.com/", "homepage_url": "https://www.drawio.com/", "icon": "Workflow", "popularity": 80, "is_open_source": True, "platforms": ["Web", "Windows", "macOS", "Linux"]},
    {"name": "Notion", "category_slug": "prod", "description": "All-in-one workspace for notes, docs, databases and project management.", "alternative_uses": ["Wiki", "CRM", "Habit tracker"], "download_url": "https://www.notion.so/desktop", "homepage_url": "https://www.notion.so/", "icon": "Layout", "popularity": 90, "platforms": ["Windows", "macOS", "Linux", "iOS", "Android", "Web"]},
    {"name": "Todoist", "category_slug": "prod", "description": "Clean, fast cross-platform to-do app with natural-language input.", "alternative_uses": ["GTD", "Habit reminders", "Shared projects"], "download_url": "https://todoist.com/downloads", "homepage_url": "https://todoist.com/", "icon": "ListChecks", "popularity": 75, "platforms": ["Windows", "macOS", "Linux", "iOS", "Android"]},
    {"name": "Standard Notes", "category_slug": "prod", "description": "Encrypted, simple, sustainable notes app. Plain text first.", "alternative_uses": ["Encrypted journaling", "Secure drafts", "Cross-device sync"], "download_url": "https://standardnotes.com/download", "homepage_url": "https://standardnotes.com/", "icon": "FileLock2", "popularity": 60, "is_open_source": True, "platforms": ["Windows", "macOS", "Linux", "iOS", "Android"]},
    {"name": "Affine", "category_slug": "prod", "description": "Open-source, all-in-one knowledge OS that blends docs, kanban and whiteboard.", "alternative_uses": ["Self-hosted Notion alt", "Visual planning", "Collab docs"], "download_url": "https://affine.pro/", "homepage_url": "https://affine.pro/", "icon": "BookMarked", "popularity": 64, "is_open_source": True, "platforms": ["Windows", "macOS", "Linux"]},

    # ================ TERMINAL ================
    {"name": "Windows Terminal", "category_slug": "terminal", "description": "Modern multi-tab terminal from Microsoft. GPU-accelerated, theme-able.", "alternative_uses": ["PowerShell + WSL combo", "SSH sessions", "Eye candy"], "download_url": "https://aka.ms/terminal", "homepage_url": "https://github.com/microsoft/terminal", "icon": "TerminalSquare", "popularity": 85, "is_open_source": True, "platforms": ["Windows"]},
    {"name": "iTerm2", "category_slug": "terminal", "description": "The macOS terminal replacement everyone secretly uses.", "alternative_uses": ["Split panes", "Inline images", "Tmux integration"], "download_url": "https://iterm2.com/", "homepage_url": "https://iterm2.com/", "icon": "Terminal", "popularity": 82, "platforms": ["macOS"]},
    {"name": "Alacritty", "category_slug": "terminal", "description": "GPU-accelerated, minimalist terminal emulator written in Rust.", "alternative_uses": ["Speed-obsessed setups", "Tiling WMs", "Dotfile flexes"], "download_url": "https://github.com/alacritty/alacritty/releases", "homepage_url": "https://alacritty.org/", "icon": "Zap", "popularity": 75, "is_open_source": True, "platforms": ["Windows", "macOS", "Linux"]},
    {"name": "WezTerm", "category_slug": "terminal", "description": "Powerful, GPU-accelerated cross-platform terminal with built-in multiplexing.", "alternative_uses": ["Built-in tmux", "SSH domains", "Lua config"], "download_url": "https://wezfurlong.org/wezterm/", "homepage_url": "https://wezfurlong.org/wezterm/", "icon": "PanelsTopLeft", "popularity": 70, "is_open_source": True, "platforms": ["Windows", "macOS", "Linux"]},
    {"name": "Warp", "category_slug": "terminal", "description": "AI-powered modern terminal with command blocks and team workflows.", "alternative_uses": ["AI-suggested commands", "Notebooks", "Shared sessions"], "download_url": "https://www.warp.dev/", "homepage_url": "https://www.warp.dev/", "icon": "Sparkles", "popularity": 78, "platforms": ["macOS", "Linux", "Windows"]},
    {"name": "tmux", "category_slug": "terminal", "description": "Terminal multiplexer. Detach sessions, split panes, never lose work to a closed SSH again.", "alternative_uses": ["Long-running jobs", "Remote dev", "Pair programming"], "download_url": "https://github.com/tmux/tmux/wiki/Installing", "homepage_url": "https://github.com/tmux/tmux", "icon": "Columns3", "popularity": 86, "is_open_source": True, "platforms": ["macOS", "Linux", "WSL"]},
    {"name": "Starship", "category_slug": "terminal", "description": "Minimal, blazing-fast, infinitely customizable prompt for any shell.", "alternative_uses": ["Git status", "K8s context", "Multi-shell uniformity"], "download_url": "https://starship.rs/", "homepage_url": "https://starship.rs/", "icon": "Star", "popularity": 80, "is_open_source": True, "platforms": ["Windows", "macOS", "Linux"]},
    {"name": "fzf", "category_slug": "terminal", "description": "Command-line fuzzy finder. Once you start using it you can't stop.", "alternative_uses": ["History search", "File picking", "Git branch jump"], "download_url": "https://github.com/junegunn/fzf", "homepage_url": "https://github.com/junegunn/fzf", "icon": "Search", "popularity": 84, "is_open_source": True, "platforms": ["macOS", "Linux", "WSL"]},
    {"name": "bat", "category_slug": "terminal", "description": "A 'cat' clone with syntax highlighting, line numbers and Git integration.", "alternative_uses": ["Reading source", "Diff highlighting", "Pretty output"], "download_url": "https://github.com/sharkdp/bat/releases", "homepage_url": "https://github.com/sharkdp/bat", "icon": "FileText", "popularity": 78, "is_open_source": True, "platforms": ["Windows", "macOS", "Linux"]},
    {"name": "Nerd Fonts", "category_slug": "terminal", "description": "Patched developer fonts with thousands of glyphs (Powerline, icons, logos).", "alternative_uses": ["Prompt icons", "Vim icons", "Statusbar flair"], "download_url": "https://www.nerdfonts.com/font-downloads", "homepage_url": "https://www.nerdfonts.com/", "icon": "Type", "popularity": 82, "is_open_source": True, "platforms": ["Windows", "macOS", "Linux"]},
]


CURATED_REPOS = [
    {
        "name": "PowerToys",
        "full_name": "microsoft/PowerToys",
        "description": "Windows system utilities to maximize productivity.",
        "url": "https://github.com/microsoft/PowerToys",
        "stars": "112k",
        "language": "C#",
        "tags": ["windows", "utilities", "productivity"],
    },
    {
        "name": "stable-diffusion-webui",
        "full_name": "AUTOMATIC1111/stable-diffusion-webui",
        "description": "Web UI for Stable Diffusion image generation.",
        "url": "https://github.com/AUTOMATIC1111/stable-diffusion-webui",
        "stars": "145k",
        "language": "Python",
        "tags": ["ai", "image-generation"],
    },
    {
        "name": "ohmyzsh",
        "full_name": "ohmyzsh/ohmyzsh",
        "description": "A delightful community-driven framework for managing your zsh configuration.",
        "url": "https://github.com/ohmyzsh/ohmyzsh",
        "stars": "175k",
        "language": "Shell",
        "tags": ["shell", "terminal", "themes"],
    },
    {
        "name": "public-apis",
        "full_name": "public-apis/public-apis",
        "description": "A collective list of free APIs for use in software and web development.",
        "url": "https://github.com/public-apis/public-apis",
        "stars": "315k",
        "language": "Python",
        "tags": ["api", "resources"],
    },
    {
        "name": "transformers",
        "full_name": "huggingface/transformers",
        "description": "State-of-the-art machine learning for PyTorch, TensorFlow, and JAX.",
        "url": "https://github.com/huggingface/transformers",
        "stars": "135k",
        "language": "Python",
        "tags": ["ai", "ml", "nlp"],
    },
    {
        "name": "llama.cpp",
        "full_name": "ggerganov/llama.cpp",
        "description": "Port of Facebook's LLaMA model in C/C++. Run LLMs on a laptop.",
        "url": "https://github.com/ggerganov/llama.cpp",
        "stars": "70k",
        "language": "C++",
        "tags": ["ai", "llm", "local"],
    },
    {
        "name": "terminal",
        "full_name": "microsoft/terminal",
        "description": "The new Windows Terminal and the original Windows console host.",
        "url": "https://github.com/microsoft/terminal",
        "stars": "95k",
        "language": "C++",
        "tags": ["terminal", "windows"],
    },
    {
        "name": "neovim",
        "full_name": "neovim/neovim",
        "description": "Vim-fork focused on extensibility and usability.",
        "url": "https://github.com/neovim/neovim",
        "stars": "82k",
        "language": "Vim Script",
        "tags": ["editor", "vim"],
    },
    {
        "name": "linux",
        "full_name": "torvalds/linux",
        "description": "Linux kernel source tree. The big one.",
        "url": "https://github.com/torvalds/linux",
        "stars": "170k",
        "language": "C",
        "tags": ["os", "kernel"],
    },
    {
        "name": "ComfyUI",
        "full_name": "comfyanonymous/ComfyUI",
        "description": "Most powerful and modular diffusion model GUI, API, and backend.",
        "url": "https://github.com/comfyanonymous/ComfyUI",
        "stars": "55k",
        "language": "Python",
        "tags": ["ai", "stable-diffusion"],
    },
    {
        "name": "awesome",
        "full_name": "sindresorhus/awesome",
        "description": "Awesome lists about all kinds of interesting topics.",
        "url": "https://github.com/sindresorhus/awesome",
        "stars": "320k",
        "language": "Markdown",
        "tags": ["resources", "lists"],
    },
    {
        "name": "FFmpeg",
        "full_name": "FFmpeg/FFmpeg",
        "description": "Mirror of https://git.ffmpeg.org/ffmpeg.git",
        "url": "https://github.com/FFmpeg/FFmpeg",
        "stars": "45k",
        "language": "C",
        "tags": ["video", "audio", "media"],
    },
    {"name": "yt-dlp", "full_name": "yt-dlp/yt-dlp", "description": "Feature-rich command-line audio/video downloader.", "url": "https://github.com/yt-dlp/yt-dlp", "stars": "78k", "language": "Python", "tags": ["video", "download"]},
    {"name": "Obsidian Plugins (awesome)", "full_name": "kmaasrud/awesome-obsidian", "description": "Curated list of resources for Obsidian.md.", "url": "https://github.com/kmaasrud/awesome-obsidian", "stars": "3k", "language": "Markdown", "tags": ["notes", "obsidian"]},
    {"name": "rustdesk", "full_name": "rustdesk/rustdesk", "description": "An open-source TeamViewer alternative written in Rust.", "url": "https://github.com/rustdesk/rustdesk", "stars": "75k", "language": "Rust", "tags": ["remote", "desktop"]},
    {"name": "starship", "full_name": "starship/starship", "description": "The minimal, blazing-fast, infinitely customizable prompt for any shell.", "url": "https://github.com/starship/starship", "stars": "42k", "language": "Rust", "tags": ["terminal", "prompt"]},
    {"name": "open-webui", "full_name": "open-webui/open-webui", "description": "User-friendly AI Interface (Supports Ollama, OpenAI API, …).", "url": "https://github.com/open-webui/open-webui", "stars": "65k", "language": "Svelte", "tags": ["ai", "ui"]},
    {"name": "tailscale", "full_name": "tailscale/tailscale", "description": "The easiest, most secure way to use WireGuard and 2FA.", "url": "https://github.com/tailscale/tailscale", "stars": "21k", "language": "Go", "tags": ["network", "vpn"]},
    {"name": "AppFlowy", "full_name": "AppFlowy-IO/AppFlowy", "description": "Open-source alternative to Notion.", "url": "https://github.com/AppFlowy-IO/AppFlowy", "stars": "60k", "language": "Dart", "tags": ["notes", "productivity"]},
    {"name": "wails", "full_name": "wailsapp/wails", "description": "Create beautiful applications using Go.", "url": "https://github.com/wailsapp/wails", "stars": "27k", "language": "Go", "tags": ["desktop", "go"]},
    {"name": "ollama", "full_name": "ollama/ollama", "description": "Get up and running with Llama 3, Mistral, Gemma 2, and other LLMs.", "url": "https://github.com/ollama/ollama", "stars": "95k", "language": "Go", "tags": ["ai", "llm"]},
    {"name": "excalidraw", "full_name": "excalidraw/excalidraw", "description": "Virtual whiteboard for sketching hand-drawn-like diagrams.", "url": "https://github.com/excalidraw/excalidraw", "stars": "84k", "language": "TypeScript", "tags": ["whiteboard", "diagrams"]},
    {"name": "fastapi", "full_name": "fastapi/fastapi", "description": "FastAPI framework, high performance, easy to learn.", "url": "https://github.com/fastapi/fastapi", "stars": "78k", "language": "Python", "tags": ["api", "framework"]},
]
